### ISSUE TITLE
[ShadowContainer/Flyout] Shadows and Background color disappearing on Flyout

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno.toolkit.ui#760] opened 2023-08-25 14:06 UTC
## Current behavior

Basically the Flyout loses background color and shadows on the second time it pops up.

https://github.com/unoplatform/uno.toolkit.ui/assets/114886335/273a4a75-099b-4d2f-a2f3-72c4240ddb76

## How to reproduce it (as minimally and precisely as possible)

Flyout Shadows added to Gallery Sample in this PR -> https://github.com/unoplatform/Uno.Gallery/pull/905:

1. [TabBar Flyout](https://github.com/unoplatform/Uno.Gallery/blob/5365a3501188fe697c701aeb7f1eacbb871ac4ce/Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml#L4256)
2. [ComboBox Flyout](https://github.com/unoplatform/Uno.Gallery/blob/5365a3501188fe697c701aeb7f1eacbb871ac4ce/Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml#L1144)

Affected platform(s):

- [X] WebAssembly
- [X] Android
- [X] iOS
- [X] Skia
- [X] Windows

**Comment by agneszitte** [comment] 2023-08-28 16:29
This one can be worked on for 5.0 as per discussion with @kazo0 (cc @jeromelaban)

**Comment by rafael-rosa-knowcode** [comment] 2023-09-15 13:26
Issue fixed.
Using Uno.Toolkit.WinUI on Version 5.0.0-dev.99.

https://github.com/unoplatform/uno.toolkit.ui/assets/116665025/1b63ac99-2bd5-410f-adc9-194edf712df8

**Comment by agneszitte** [comment] 2023-09-15 15:07
Thanks @rafael-rosa-knowcode 
@sakshi173 can you please review this issue on both 4X and 5X canaries please

**Comment by sakshi173** [comment] 2023-11-21 04:41
I am not able to reproduce this issue, closing it.

**Closed by sakshi173** 2023-11-21 04:41 UTC
Labels: kind/bug, triage/untriaged, control/shadows
