### ISSUE TITLE
[Skia / iOS] ShadowContainer re-layout issue

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno.toolkit.ui#748] opened 2023-08-22 15:47 UTC
_Originally posted by @kazo0 in https://github.com/unoplatform/uno.toolkit.ui/pull/737#pullrequestreview-1589694888_

> I'm seeing some strange behaviors if I add an extra shadow using the ShadowContainerSamplePage here (tested on Skia so far):
> 
> Before adding new shadow:
> ![image](https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/4bcbb18d-fcf3-4179-8651-12f04363d4a2)
> 
> After adding new shadow:
> ![image](https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/40d9c42b-4d38-4ea0-8b6b-15269c96f0c6)
>
> It seems to also break on `main` but in a different way: 
> Before adding new shadow:
> ![image](https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/17a2ce53-9c47-47bb-b44b-5eb05013c5fc)
>
> After adding new shadow:
> ![image](https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/ed4e7872-49ff-4c70-9c62-a22be3ab907d)
>
> Not sure if it's really related to these changes but something is different

**Comment by Xiaoy312** [comment] 2023-08-22 16:13
@kazo0 @agneszitte
is this required for 4.10?

**Comment by kazo0** [comment] 2023-08-22 16:56
Might not be highest prio since its contained to just Skia

**Comment by kazo0** [comment] 2023-08-22 17:16
To recap:

We are seeing the following effect when adding a third shadow to the sample control when clicking the Add Shadow button on Skia.GTK

![image](https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/48cfccf4-a586-4bff-8d59-9ff7dbe2a60e)

It should look like this:

<img width="343" alt="image" src="https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/c67185e5-2380-47c2-bfa6-3b76ea537d2d">

**Comment by Marc-Antoine-Soucy** [comment] 2023-08-24 13:54
Here's a summary of the result of my investigation: 
1: The problem is related to the change in height of the child of the shadow container, only adding a shadow does not create any problem. 

2:  Even if the only thing you call in OnShadowCollectionChanged is OnShadowSizeChanged(); (after adding InvalidateFromShadowPropertyChange(); to OnShadowSizeChanged) , the shadow will disappear when you change you change the size of the child item, but will reappear when you add a shadow. 

3: When you add numbers to the childheight in the OnShadowSizeChanged event, it will not have a meanigful impact on anything.

4: the bug is still Present on main, it's just that it's only present for a few frame. 
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/90481654/b11b1ec3-0cd5-46c4-a093-c0448bdf5433)
![shadow](https://github.com/unoplatform/uno.toolkit.ui/assets/90481654/fe9dbe37-dd98-42f3-ac88-601b54a2869f)

**Comment by Xiaoy312** [comment] 2023-08-25 05:59
```
@xy ===== UpdateCanvasSize
@xy _canvas.Size: 332.65625x334
@xy _shadowHost.Size: 392.65625x394
@xy _shadowHost.CanvasOffset: @-30,-30
@xy ===== UpdateCanvasSize
@xy _canvas.Size: 332.65625x461
@xy _shadowHost.Size: 392.65625x521
@xy _shadowHost.CanvasOffset: @-30,-30
@xy ===== InvalidateShadows
@xy ===== OnSurfacePainted
@xy _shadowHost.Size: 392.65625x521
@xy _shadowHost.ActualSize: 392.65625x394
@xy NeedsPaint() => true
@xy ===== OnSurfacePainted
@xy _shadowHost.Size: 392.65625x521
@xy _shadowHost.ActualSize: 392.65625x521
@xy NeedsPaint() => false
```
the issue happen when we quickly set _shadowHost.Width and Height in rapid succession
the actual size lags behind on the 1st paint pass, causing us to paint with the wrong values
(`e.Info.Width/Height` is derived from _shadowHost actual-size)
and then, the 2nd paint pass (that would have the updated values) got skipped by `!NeedsPaint(...)` since the paint state didnt change since last pass

**Comment by Xiaoy312** [comment] 2023-08-25 06:02
we can properly bypass the 1st call with:
```
if (_shadowHost.Width != _shadowHost.ActualWidth ||
	_shadowHost.Height != _shadowHost.ActualHeight)
{
	return;
}
```
^ would need to check if there are case that will cause Size!=ActualSize like other h/v-stretch mode?

**Comment by jeromelaban** [comment] 2023-08-25 14:16
> ^ would need to check if there are case that will cause Size!=ActualSize like other h/v-stretch mode?

Couldn't the Width/Height be `NaN` in which case this particular set of condition always be true?

**Comment by Xiaoy312** [comment] 2023-08-25 15:26
we do hard code them here:
https://github.com/unoplatform/uno.toolkit.ui/blob/main/src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.cs#L209C38-L209C38

**Comment by agneszitte** [comment] 2023-08-31 02:04
Re-Open for backports

**Comment by Xiaoy312** [comment] 2023-08-31 04:02
this issue issue was kept opened because:
> let's merge this PR if it's approved by the rest of the team, but make sure to add a create a new PR right after that will add regression testing. I've removed the automatic closing of the issue so we can keep track of this.
> -- Jerome

**Comment by agneszitte** [comment] 2023-09-01 03:04
Closing issue now that all the backports are done.
Related Tests will be done with #791

**Closed by agneszitte** 2023-09-01 03:04 UTC
Labels: control/shadows
