### ISSUE TITLE
ExtendedSplashScreen throws exception running as unpackaged

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.toolkit.ui#1165] opened 2024-06-24 05:16 UTC
## Current behavior

When running Windows as unpackaged, the ExtendedSplashScreen control throws an internal exception (ie one that is caught) when attempting to load the AppxManifest.xml file (which does exist in the publish folder).

Issue seems to be with the "file:\" prefix that's at the beginning of the directory name returned for the executing assembly.
file:\C:\source\github\unoplatform\Uno.Platform\testing\TestHarness\TestHarness.Windows\bin\x64\Debug\net8.0-windows10.0.19041.0\win-x64\AppxManifest.xml

System.ArgumentException
  HResult=0x80070057
  Message=Value does not fall within the expected range.

![image](https://github.com/unoplatform/uno.toolkit.ui/assets/1614057/c75cf661-00d9-4c6b-bd3f-c0650eb5ebff)

## Expected behavior

AppxManifest.xml file exists, so this methods should return the correct path to the corresponding file.

## How to reproduce it (as minimally and precisely as possible)

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

IDE:

- [ ] Visual Studio 2022
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] Visual Studio for Mac
- [ ] Rider Windows
- [ ] Rider macOS

Relevant plugins:

## Anything else we need to know?

 	System.Private.CoreLib.dll!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() Line 53	C#
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) Line 154	C#
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task, System.Threading.Tasks.ConfigureAwaitOptions options) Line 118	C#
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter<System.__Canon>.GetResult() Line 335	C#
 	[Waiting on Async Operation, double-click or press enter to view Async Call Stacks]	
>	Uno.Toolkit.WinUI.dll!Uno.Toolkit.UI.ExtendedSplashScreen.ApplicationPathFromFileName(System.Reflection.Assembly entry, string fileName) Line 300	C#
 	Uno.Toolkit.WinUI.dll!Uno.Toolkit.UI.ExtendedSplashScreen.LoadManifestFromPackageFile(System.Reflection.Assembly entry, string manifestFile) Line 247	C#
 	Uno.Toolkit.WinUI.dll!Uno.Toolkit.UI.ExtendedSplashScreen.LoadAppManifest(System.Reflection.Assembly entry, string[] manifestFiles) Line 228	C#
 	Uno.Toolkit.WinUI.dll!Uno.Toolkit.UI.ExtendedSplashScreen.LoadSplashScreenFromPackageManifest(Microsoft.UI.Xaml.Controls.Image splashScreenImage, Microsoft.UI.Xaml.Media.SolidColorBrush splashScreenBackground) Line 196	C#
 	Uno.Toolkit.WinUI.dll!Uno.Toolkit.UI.ExtendedSplashScreen.GetNativeSplashScreen() Line 130	C#
 	Uno.Toolkit.WinUI.dll!Uno.Toolkit.UI.ExtendedSplashScreen.LoadNativeSplashScreen() Line 85	C#
 	Uno.Toolkit.WinUI.dll!Uno.Toolkit.UI.ExtendedSplashScreen.OnApplyTemplate() Line 79	C#
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.OnApplyTemplate()	Unknown
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_OnApplyTemplate_2(nint thisPtr)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride(WinRT.IObjectReference _obj, Windows.Foundation.Size availableSize)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Windows.Foundation.Size availableSize)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Windows.Foundation.Size availableSize)	Unknown
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(nint thisPtr, Windows.Foundation.Size availableSize, Windows.Foundation.Size* result)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference _obj, Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	TestHarnessApp.dll!TestHarness.Program.Main(string[] args) Line 32	C#

**Comment by agneszitte** [comment] 2024-07-12 02:44
I am not getting the exception mentioned on this issue here for WinAppSDK Unpackaged with the latest versions but I noticed that the splashscreen image is not visible for the ExtendedSplashScreen. 
Details here: https://github.com/unoplatform/uno.toolkit.ui/issues/1185

**Comment by agneszitte** [comment] 2024-07-16 17:22
> I am not getting the exception mentioned on this issue here for WinAppSDK Unpackaged with the latest versions but I noticed that the splashscreen image is not visible for the ExtendedSplashScreen. Details here: #1185

@nickrandolph let me know if you are able to replicate the exception now that https://github.com/unoplatform/uno.toolkit.ui/pull/1188 is merged please

**Comment by Xiaoy312** [comment] 2024-07-17 04:26
#1188 wont fix it, and
we need a repro to begin investigation

**Comment by agneszitte** [comment] 2024-07-17 20:41
> #1188 wont fix it, and we need a repro to begin investigation

I know, I mentioned I am not able to reproduce the exception on my side.

@nickrandolph we will need more info please if you are still able to reproduce it please

**Comment by nickrandolph** [comment] 2024-07-30 13:46
@kazo0 / @eriklimakc  are you able to take a look at this please?

**Comment by eriklimakc** [comment] 2024-07-31 12:14
I can repro this exception with a new app created by the wizard with the recommended template. The "Common Language Runtime Exceptions" option must be checked. The file "AppxManifest.xml" exists on the directory specified.

I will try to do some investigation.

@nickrandolph @kazo0 @agneszitte

**Closed** 2024-08-07 13:37 UTC
Labels: kind/bug, control/loadingview-splashscreen
