### ISSUE TITLE
TimePicker implemented in WASM and Skia.

### ISSUE THREAD

**Issue by ADD-Eugenio-Lopez** [unoplatform/uno.toolkit.ui#632] opened 2023-06-30 11:41 UTC
## What would you like to be added:
The implementation of TimePicker for WASM and Skia.

## Why is this needed:
Because this control is basic for register data in data forms.

## For which Platform:

- [X] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [X] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

**Comment by jeromelaban** [comment] 2023-07-10 12:57
Thanks for the report. This is a duplicate of https://github.com/unoplatform/uno/issues/5553

**Closed by jeromelaban** 2023-07-10 12:57 UTC
Labels: kind/enhancement, triage/untriaged
